#!/usr/bin/env tsx
/**
 * Chia coverage metric: how much of the real world does the condition
 * language reach?
 *
 * Downloads the Chia corpus (Kury et al. 2020, CC-BY-4.0) — 1,000 Phase IV
 * trials, ~12,400 annotated eligibility criteria — from the `bigbio/chia`
 * mirror on HuggingFace, classifies every criterion line as expressible /
 * partially / unmodeled against rulekit's closed condition language, and
 * writes docs/chia-coverage.md.
 *
 * The download is the 2.4 MB BRAT archive rather than the parquet export: the
 * `.txt` files are one criterion per line, which is exactly the unit being
 * counted, and it needs no datasets library.
 *
 * The classification is heuristic — surface patterns, no human labels. The
 * classifier and its limits are documented in scripts/lib/chia.ts, and the
 * generated report repeats the caveat prominently.
 *
 *   npx tsx scripts/chia-coverage.ts [--force] [--out docs/chia-coverage.md]
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { classifyCriterion, pct, splitCriteria, tally } from "./lib/chia.js";
import type { Classification, CoverageClass } from "./lib/chia.js";
import { REPO_ROOT } from "./lib/paths.js";

const CHIA_URL = "https://huggingface.co/datasets/bigbio/chia/resolve/main/data/chia_without_scope.zip";
const CHIA_DIR = join(REPO_ROOT, "data", "chia");
const ZIP_PATH = join(CHIA_DIR, "chia_without_scope.zip");
const EXAMPLES_PER_CLASS = 10;

async function ensureCorpus(force: boolean): Promise<string> {
  const brat = join(CHIA_DIR, "brat");
  if (!force && existsSync(brat) && readdirSync(brat).some((f) => f.endsWith(".txt"))) return brat;

  mkdirSync(CHIA_DIR, { recursive: true });
  if (force || !existsSync(ZIP_PATH)) {
    process.stderr.write(`downloading ${CHIA_URL}\n`);
    const res = await fetch(CHIA_URL);
    if (!res.ok) throw new Error(`GET ${CHIA_URL} -> ${res.status} ${res.statusText}`);
    writeFileSync(ZIP_PATH, Buffer.from(await res.arrayBuffer()));
  }
  rmSync(brat, { recursive: true, force: true });
  mkdirSync(brat, { recursive: true });
  for (const [cmd, args] of [
    ["unzip", ["-q", "-o", ZIP_PATH, "-d", brat]],
    ["tar", ["-x", "-f", ZIP_PATH, "-C", brat]],
  ] as const) {
    if (spawnSync(cmd, args, { stdio: "inherit" }).status === 0) return brat;
  }
  throw new Error(`could not unzip ${ZIP_PATH}`);
}

type Row = Classification & { nctId: string; kind: "inclusion" | "exclusion" };

function classifyCorpus(dir: string): Row[] {
  const rows: Row[] = [];
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".txt")).sort()) {
    const match = /^(NCT\d+)_(inc|exc)\.txt$/.exec(file);
    if (!match) continue;
    const [, nctId, tag] = match;
    for (const text of splitCriteria(readFileSync(join(dir, file), "utf8"))) {
      rows.push({ ...classifyCriterion(text), nctId: nctId as string, kind: tag === "inc" ? "inclusion" : "exclusion" });
    }
  }
  return rows;
}

/** Spread examples across trials so one verbose protocol cannot fill a class. */
function examples(rows: readonly Row[], klass: CoverageClass, n: number): Row[] {
  const seen = new Set<string>();
  const picked: Row[] = [];
  for (const r of rows.filter((r) => r.klass === klass)) {
    if (seen.has(r.nctId)) continue;
    seen.add(r.nctId);
    picked.push(r);
    if (picked.length === n) break;
  }
  return picked;
}

const signalCounts = (rows: readonly Row[], field: "anchors" | "blockers"): [string, number][] => {
  const counts = new Map<string, number>();
  for (const r of rows) for (const s of r[field]) counts.set(s, (counts.get(s) ?? 0) + 1);
  return [...counts.entries()].sort((a, b) => b[1] - a[1]);
};

function report(rows: Row[]): string {
  const total = rows.length;
  const t = tally(rows);
  const trials = new Set(rows.map((r) => r.nctId)).size;
  const inc = rows.filter((r) => r.kind === "inclusion");
  const exc = rows.filter((r) => r.kind === "exclusion");
  const row = (label: string, set: readonly Row[]): string => {
    const s = tally(set);
    return `| ${label} | ${set.length} | ${pct(s.expressible, set.length)}% | ${pct(s.partially, set.length)}% | ${pct(s.unmodeled, set.length)}% |`;
  };

  const section = (klass: CoverageClass, heading: string, gloss: string): string =>
    [
      `### ${heading}`,
      "",
      gloss,
      "",
      ...examples(rows, klass, EXAMPLES_PER_CLASS).map(
        (r) =>
          `- *${r.nctId} (${r.kind})* — "${r.text.length > 260 ? `${r.text.slice(0, 257)}...` : r.text}"  \n  ` +
          `anchors: ${r.anchors.join(", ") || "none"} · blockers: ${r.blockers.join(", ") || "none"}`,
      ),
    ].join("\n");

  return `# Chia coverage — how much of the real world does the condition language reach?

**Generated by \`npx tsx scripts/chia-coverage.ts\`. Do not hand-edit.**

> **This classification is heuristic.** It matches surface patterns in the
> criterion text — it does not parse the criteria, does not attempt to write
> the rules, and has not been validated against human labels. Read the
> percentages as an order-of-magnitude sanity check on whether the condition
> language is sized right, and nothing stronger. The classifier's rules, and
> a worked example of it disagreeing with a human rule author, are below.

## Corpus

[Chia](https://github.com/WengLab-InformaticsResearch/CHIA) (Kury et al.,
*Scientific Data* 2020, CC-BY-4.0), via the \`bigbio/chia\` mirror on
HuggingFace. **${total.toLocaleString()} criterion lines** across
**${trials.toLocaleString()} trials** (Phase IV, registered on ClinicalTrials.gov).
One line = one criterion, as the corpus authors segmented them.

## Result

| Set | Criteria | Expressible | Partially | Unmodeled |
|---|---:|---:|---:|---:|
${row("All", rows)}
${row("Inclusion", inc)}
${row("Exclusion", exc)}

**${pct(t.expressible, total)}% of real criteria are expressible** in the closed
condition language as written, a further **${pct(t.partially, total)}%** carry an
expressible core inside a sentence that also says something the language cannot
(these are the \`unmodeled: true\` judgement calls a rule author has to make),
and **${pct(t.unmodeled, total)}%** offer nothing to compare at all.

Inclusion and exclusion criteria fail the language in different ways:
exclusions wrap a modelable core in judgement about
${(Number(pct(tally(exc).partially, exc.length)) / Math.max(0.1, Number(pct(tally(inc).partially, inc.length)))).toFixed(1)}x
as often as inclusions do (partially: ${pct(tally(exc).partially, exc.length)}% vs
${pct(tally(inc).partially, inc.length)}%), while inclusions more often name nothing
the language can compare at all (unmodeled: ${pct(tally(inc).unmodeled, inc.length)}% vs
${pct(tally(exc).unmodeled, exc.length)}%).

## Method

Two pattern lists, applied to each criterion:

- **anchors** — features that give a rule something concrete to compare: a
  numeric threshold, a unit, a named lab or score, a diagnosis or medication
  reference, a named clinical condition (a bare code set such as "Pregnant or
  lactating" needs no trigger word), an explicit time window, age, sex.
- **blockers** — features no closed condition language can express:
  investigator judgement, vague qualifiers ("adequate", "clinically
  significant", "stable"), consent and logistics, open-ended lists ("such as,
  but not limited to"), intent and planning, exception clauses, prognosis, and
  "would interfere with" constructions.

Then:

| Anchors | Blockers | Class |
|---|---|---|
| none | any | unmodeled |
| ≥ 1 | none | expressible |
| ≥ 1 | ≥ 1 | partially |

Most frequent anchors: ${signalCounts(rows, "anchors").slice(0, 5).map(([s, n]) => `\`${s}\` (${n.toLocaleString()})`).join(", ")}.

Most frequent blockers: ${signalCounts(rows, "blockers").slice(0, 5).map(([s, n]) => `\`${s}\` (${n.toLocaleString()})`).join(", ")}.

## Known biases

- **It reads sentences, not meaning.** A criterion whose every word is codable
  but whose *combination* is not will be scored expressible.
- **It is optimistic relative to a rule author.** COMMANDER HF's E5, "Planned
  intermittent outpatient treatment with positive inotropic drugs administered
  intravenously", was marked \`unmodeled: true\` by hand — a plan is not an
  event and no extract records one — while the classifier sees "treatment
  with <drug class>" and scores it *partially*. Expect the true expressible
  share to be at or below the number above, not higher.
- **It also under-counts.** Criteria that name only a procedure, a device or a
  drug allergy — "CABG or Percutaneous Coronary Intervention", "Hypersensitivity
  to camptothecin" — are code sets in practice but match no anchor, and land in
  *unmodeled*. The two biases push in opposite directions and are not netted
  out here.
- **Segmentation is Chia's, not ours.** A line holding three clauses counts
  once.
- **Phase IV only.** Chia samples Phase IV trials; earlier-phase oncology
  protocols carry heavier eligibility text.

## Examples

${section("expressible", "Expressible", "A threshold, a code set, or a time window, and nothing else in the sentence.")}

${section("partially", "Partially expressible", "A modelable core wrapped in something the language cannot say. These are where `unmodeled: true` becomes a judgement call.")}

${section("unmodeled", "Unmodeled", "Nothing to compare: consent, logistics, judgement, or a clinical state with no structured correlate.")}
`;
}

async function main(argv: string[]): Promise<void> {
  const force = argv.includes("--force");
  const outIdx = argv.indexOf("--out");
  const out = join(REPO_ROOT, (outIdx === -1 ? undefined : argv[outIdx + 1]) ?? join("docs", "chia-coverage.md"));

  const dir = await ensureCorpus(force);
  const rows = classifyCorpus(dir);
  if (rows.length === 0) throw new Error(`no criteria parsed out of ${dir}`);

  mkdirSync(join(out, ".."), { recursive: true });
  writeFileSync(out, report(rows));

  const t = tally(rows);
  process.stderr.write(
    `classified ${rows.length} criteria from ${new Set(rows.map((r) => r.nctId)).size} trials\n` +
      `  expressible ${pct(t.expressible, rows.length)}%  partially ${pct(t.partially, rows.length)}%  ` +
      `unmodeled ${pct(t.unmodeled, rows.length)}%\n  wrote ${out}\n`,
  );
}

main(process.argv.slice(2)).catch((err: unknown) => {
  process.stderr.write(`${String(err)}\n`);
  process.exit(1);
});
