#!/usr/bin/env tsx
/**
 * Stage 2: `corpus/patients/` -> `corpus/messy/`.
 *
 * Seeded, deterministic corruption that makes the clean Synthea corpus
 * resemble a real EHR extract: units dropped, LOINC replaced with site-local
 * codes, lab values stringified (">60"), medication rows duplicated,
 * timestamps backdated. Same seed, same corpus, byte for byte.
 *
 * The corruption itself lives in scripts/lib/mess.ts and is unit-tested; this
 * is the CLI. Each output file carries a comment header listing exactly what
 * was done to that patient, so the messy corpus is self-documenting and the
 * clean/messy diff is readable in review.
 *
 *   npx tsx scripts/mess-injector.ts [--seed 42] [--in corpus/patients] [--out corpus/messy]
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { stringify } from "yaml";
import { parsePatient } from "../src/core/schema.js";
import { messPatient } from "./lib/mess.js";
import type { MessOp } from "./lib/mess.js";
import { REPO_ROOT } from "./lib/paths.js";

function opt(argv: string[], name: string, fallback: string): string {
  const i = argv.indexOf(`--${name}`);
  const v = i === -1 ? undefined : argv[i + 1];
  return v ?? fallback;
}

function main(argv: string[]): void {
  const seed = Number(opt(argv, "seed", "42"));
  if (!Number.isFinite(seed)) throw new Error("--seed needs a number");
  const inDir = join(REPO_ROOT, opt(argv, "in", join("corpus", "patients")));
  const outDir = join(REPO_ROOT, opt(argv, "out", join("corpus", "messy")));

  const files = readdirSync(inDir).filter((f) => f.endsWith(".yaml")).sort();
  if (files.length === 0) throw new Error(`no patients in ${inDir} — run scripts/flatten-synthea.ts first`);

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const totals = new Map<MessOp, number>();
  let untouched = 0;
  for (const f of files) {
    const clean = parsePatient(readFileSync(join(inDir, f), "utf8"));
    const { patient, log } = messPatient(clean, seed);
    for (const rec of log) totals.set(rec.op, (totals.get(rec.op) ?? 0) + 1);
    if (log.length === 0) untouched++;

    const header = [
      `rulekit corpus patient — MESSY. Generated by scripts/mess-injector.ts --seed ${seed}.`,
      `Source: corpus/patients/${f}. Do not hand-edit; regenerate instead.`,
      log.length === 0 ? "corruptions: none (this patient drew no mess)" : "corruptions:",
      ...log.map((r) => `  ${r.op}: ${r.target} — ${r.detail}`),
    ];
    writeFileSync(
      join(outDir, f),
      `${header.map((l) => `# ${l}`).join("\n")}\n${stringify(patient, { lineWidth: 0, sortMapEntries: false })}`,
    );
  }

  const summary = [...totals.entries()].sort().map(([op, n]) => `${op}=${n}`).join(" ");
  process.stderr.write(
    `messed ${files.length} patients (seed ${seed}) into ${outDir}\n` +
      `  ${summary}\n  ${untouched} patients drew no corruption\n`,
  );
}

try {
  main(process.argv.slice(2));
} catch (err: unknown) {
  process.stderr.write(`${String(err)}\n`);
  process.exit(1);
}
