#!/usr/bin/env tsx
/**
 * Stage 3: `corpus/messy/` -> `corpus/normalized/`.
 *
 * The cleaning half of ingestion — UCUM unit normalization, local-code ->
 * LOINC mapping, and quarantine of anything that cannot be trusted as a
 * number. The normalized corpus is the one the engine should evaluate.
 *
 * Deviation from the design spec, deliberate: the spec resolves codes and
 * units through the free NLM APIs. This build resolves them from committed
 * tables in scripts/mappings/ instead, so the pipeline is network-free and
 * reproducible in CI. See the header of scripts/mappings/local-to-loinc.yaml.
 *
 * The transformation lives in scripts/lib/normalize.ts and is unit-tested;
 * this is the CLI. Each output file lists, in a comment header, every repair
 * and every quarantine applied to that patient.
 *
 *   npx tsx scripts/normalize.ts [--in corpus/messy] [--out corpus/normalized]
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { stringify } from "yaml";
import { parsePatient } from "../src/core/schema.js";
import { normalizePatient } from "./lib/normalize.js";
import type { NormalizeKind } from "./lib/normalize.js";
import { REPO_ROOT } from "./lib/paths.js";

function opt(argv: string[], name: string, fallback: string): string {
  const i = argv.indexOf(`--${name}`);
  const v = i === -1 ? undefined : argv[i + 1];
  return v ?? fallback;
}

function main(argv: string[]): void {
  const inDir = join(REPO_ROOT, opt(argv, "in", join("corpus", "messy")));
  const outDir = join(REPO_ROOT, opt(argv, "out", join("corpus", "normalized")));

  const files = readdirSync(inDir).filter((f) => f.endsWith(".yaml")).sort();
  if (files.length === 0) throw new Error(`no patients in ${inDir} — run scripts/mess-injector.ts first`);

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const totals = new Map<NormalizeKind, number>();
  let quarantinedPatients = 0;
  for (const f of files) {
    const messy = parsePatient(readFileSync(join(inDir, f), "utf8"));
    const { patient, log } = normalizePatient(messy);
    for (const rec of log) totals.set(rec.kind, (totals.get(rec.kind) ?? 0) + 1);
    if (log.some((l) => l.kind.startsWith("quarantined") || l.kind === "unknown-unit" || l.kind === "unresolvable-code")) {
      quarantinedPatients++;
    }

    const header = [
      `rulekit corpus patient — NORMALIZED. Generated by scripts/normalize.ts.`,
      `Source: ${opt(argv, "in", join("corpus", "messy"))}/${f}. Do not hand-edit; regenerate instead.`,
      `Quarantined facts are omitted and kept as <fact>_raw, so the evaluator sees "unknown" rather than a guess.`,
      log.length === 0 ? "repairs: none needed" : "repairs:",
      ...log.map((r) => `  ${r.kind}: ${r.target} — ${r.detail}`),
    ];
    writeFileSync(
      join(outDir, f),
      `${header.map((l) => `# ${l}`).join("\n")}\n${stringify(patient, { lineWidth: 0, sortMapEntries: false })}`,
    );
  }

  const summary = [...totals.entries()].sort().map(([k, n]) => `${k}=${n}`).join(" ");
  process.stderr.write(
    `normalized ${files.length} patients into ${outDir}\n` +
      `  ${summary}\n  ${quarantinedPatients} patients carry at least one quarantined fact\n`,
  );
}

try {
  main(process.argv.slice(2));
} catch (err: unknown) {
  process.stderr.write(`${String(err)}\n`);
  process.exit(1);
}
